"""Span Alignment Module.

Why It Exists:
    Maps BioBERT character-level entity spans to Whisper ASR word boundaries.
    Because Whisper outputs word-level timestamps and entropy scores, we must
    align the character offsets generated by BioBERT back to the Whisper words
    to correctly associate timestamps and ASR confidence/entropy with each entity.

Teammate Dependencies:
    - Ankit (ASR Lead): Consumes `ASRTranscriptInput` with word boundaries.
    - Divya (Retrieval Lead): Uses aligned entities for accurate phonetic search.

Imported By:
    - Pipeline integration entrypoints.
    - `care_asr.validation.candidate_evaluator`
"""

import logging
from typing import Any

from care_asr.contracts.asr_input import ASRTranscriptInput

logger = logging.getLogger(__name__)


class SpanAligner:
    """Aligns BioBERT entity character spans to ASR word boundary objects.

    Implements an efficient O(N + M) scan across sorted entities and words
    to identify overlaps, allowing multiple ASR words to be bound to a single
    entity span and vice versa.
    """

    def __init__(self) -> None:
        logger.info("Initializing SpanAligner...")

    def align_entities_to_words(
        self, entities: list[dict[str, Any]], asr_input: ASRTranscriptInput
    ) -> list[dict[str, Any]]:
        """Maps BioBERT entity character offsets to Whisper ASR word objects.

        Iterates over the provided entities and Whisper words to find character range
        overlaps. Computes aggregated ASR confidence and entropy for the matched span.

        Args:
            entities (list[dict[str, Any]]): List of extracted BioBERT entity dictionaries.
                Expected to be sorted by `start_char`.
            asr_input (ASRTranscriptInput): Payload containing raw transcript and sorted words.

        Returns:
            list[dict[str, Any]]: List of aligned entity records containing:
                - entity (dict): The original BioBERT entity.
                - aligned_words (list[dict]): List of overlapping Whisper word dictionaries.
                - average_asr_confidence (float): Mean ASR confidence of aligned words.
                - maximum_entropy (float): Maximum ASR entropy of aligned words.
                - start_time (float): Start timestamp in seconds.
                - end_time (float): End timestamp in seconds.

        Examples:
            >>> aligner = SpanAligner()
            >>> results = aligner.align_entities_to_words(entities, asr_input)
            >>> len(results) == len(entities)
            True
        """
        logger.debug(f"Aligning {len(entities)} entities to {len(asr_input.words)} ASR words...")

        aligned_results: list[dict[str, Any]] = []
        words = asr_input.words

        # Two-pointer approach for O(N + M) time complexity
        word_idx = 0
        num_words = len(words)

        # Sort entities by start_char just in case they aren't strictly sorted
        sorted_entities = sorted(entities, key=lambda x: x.get("start_char", 0))

        for entity in sorted_entities:
            e_start = entity["start_char"]
            e_end = entity["end_char"]

            # Advance word_idx until the word is no longer entirely before the entity.
            # We strictly check <= to allow trailing punctuation attached to prior words to not overlap.
            while word_idx < num_words and words[word_idx].end_char <= e_start:
                word_idx += 1

            # Collect overlapping words
            overlapping_words = []
            temp_idx = word_idx

            # A word overlaps if it starts strictly before the entity ends
            while temp_idx < num_words and words[temp_idx].start_char < e_end:
                overlapping_words.append(words[temp_idx])
                temp_idx += 1

            # Compute aggregates
            if overlapping_words:
                avg_conf = sum(w.confidence for w in overlapping_words) / len(overlapping_words)
                max_entropy = max(w.entropy for w in overlapping_words)
                start_time = overlapping_words[0].start_time
                end_time = overlapping_words[-1].end_time
            else:
                logger.warning(
                    f"Entity '{entity.get('entity_text')}' at [{e_start}:{e_end}] "
                    "did not overlap with any ASR words."
                )
                avg_conf = 0.0
                max_entropy = 0.0
                start_time = 0.0
                end_time = 0.0

            aligned_results.append(
                {
                    "entity": entity,
                    "aligned_words": [w.model_dump() for w in overlapping_words],
                    "average_asr_confidence": round(avg_conf, 4),
                    "maximum_entropy": round(max_entropy, 4),
                    "start_time": round(start_time, 3),
                    "end_time": round(end_time, 3),
                }
            )

        logger.info(f"Successfully aligned {len(aligned_results)} entities.")
        return aligned_results
